### ISSUE TITLE
Broadcast operation verification is not working in task examples

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#190]

**Comment by vibhatha** [comment]
@supunkamburugamuve 
Batch and Streaming both?
In task examples or comms examples?

**Comment by vibhatha** [comment]
I will fix those issues.

**Comment by vibhatha** [comment]
@supunkamburugamuve 
Under review pull request : [](https://github.com/DSC-SPIDAL/twister2/pull/192)
