### ISSUE TITLE
Communicator nextEdge() gives an incremented value

### ISSUE THREAD

**Issue by nirandaperera** [DSC-SPIDAL/twister2#519]
Communicator nextEdge() gives an incremented value. because of this, we can not create edge operations, out of order in different workers. 
ex: consider the following flow for 2 workers
src[2] --gather--> comp0[1] --direct--> comp1[1] 
when this is built, in this order, gather would receive edgeValue=0 from communicator in both the workers. 
BUT, 
if this was built in the following order, 
comp1[1] <--direct-- comp0[1] <--gather-- src[2] 
worker0 would perform comp1, comp0 and src, and worker1 would perform src. and therefore, worker0 would assign direct=0, gather=1 whereas worker1 would assign gather=0 (because it does not have any other operation) 

possible solution: assign a deterministic edgeValue 
ex: hash(source name + edge name + target name)

**Comment by chathurawidanage** [comment]
If this is the case, should we expect the same issue in a job having multiple task graphs, even if we process ops in the correct order? (top to bottom)

TG1
src[2] --gather(w0:0, w1:0)--> comp0[1] --direct(w0:1)--> comp1[1]

TG2
src[2] --gather(w0:2,w1:1)--> comp0[1] --direct(w0:3)--> comp1[1]

**Comment by nirandaperera** [comment]
Yes. I think it would be the case. Actually there has to be a comm that alters the parallelism in the downstream task. If parallelism is the same throughout, then I think it should be fine. That could be the case why allgather works without an issue.

**Comment by chathurawidanage** [comment]
https://github.com/DSC-SPIDAL/twister2/pull/520
