### ISSUE TITLE
duplicated classes for comm operations 

### ISSUE THREAD

**Issue by nirandaperera** [DSC-SPIDAL/twister2#537]
there are 2 final classes with just strings for the communication operations 
edu.iu.dsc.tws.api.task.Operations
edu.iu.dsc.tws.api.comms.OperationNames

I think these can be replaced by an enum

**Comment by chathurawidanage** [comment]
@nirandaperera ayya, Did you fix this issue? I couldn't find edu.iu.dsc.tws.api.task.Operations class.

**Comment by supunkamburugamuve** [comment]
I think we need the string names as we may add the capability to add user defined operations
