### ISSUE TITLE
Add support to get data inputs to dataflow graph

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#560]
I think this may need a design dicussion

**Comment by nirandaperera** [comment]
are we thinking about this beyond the existing executor inputs impl?

**Comment by supunkamburugamuve** [comment]
Yes, when we need to schedule the graph, we need to consider its data inputs. So I think we need to have a mechanism to declare the inputs first (with the task graph) and add them at the runtime using the current method.

**Comment by chathurawidanage** [comment]
> So I think we need to have a mechanism to declare the inputs first (with the task graph) and add them at the runtime using the current method.

This capability is already there. These methods are _default_ only to prevent existing examples from breaking. Once it is finalized, examples should be migrated and _default_ can be removed.

https://github.com/DSC-SPIDAL/twister2/blob/515f7d7aff45f2915c8332021495223019a82dd0/twister2/api/src/java/edu/iu/dsc/tws/api/task/modifiers/Collector.java#L50

https://github.com/DSC-SPIDAL/twister2/blob/515f7d7aff45f2915c8332021495223019a82dd0/twister2/api/src/java/edu/iu/dsc/tws/api/task/modifiers/Receptor.java#L64

**Comment by supunkamburugamuve** [comment]
This is great. But I think they are mostly for the runtime. Isn't it a separate issue to declare them at the Taskgraph creation time. If we have that declaration we can use it at the scheduler.

**Comment by supunkamburugamuve** [comment]
Sorry I didn't check the interface properly. I think you have the declaration in the Collector interface as well. Should we move the declaration to the task graph creation time?
