### ISSUE TITLE
LOG should be WARNING or INFO

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#644]
[2019-09-24 12:33:58 -0400] [SEVERE] [-] [main] edu.iu.dsc.tws.rsched.utils.JobUtils: Job ID assigned : edu.iu.dsc.tws.examples.comms.stream.SReduceExample-f8f5d991-a510-4647-bc58-c1d0c7b96007 

This log should be a WARNING or INFO

**Comment by chathurawidanage** [comment]
Hi,

This log is SEVERE, because this should be printed out in the log at any
log level. Users need this information for fault tolerance.

Regards,
Chathura

**Comment by chathurawidanage** [comment]
This log is SEVERE, because this should be printed out in the log at any log level. Users need this information for fault tolerance.

**Comment by supunkamburugamuve** [comment]
Is there a way to configure a specific logger for this package and set it to INFO so that this gets printed when user changes the Logging for other packages.

**Comment by chathurawidanage** [comment]
Yes.. we can add an additional configuration in logger.properties. But users can override that with root level log configs. This can be easily fixed by adding a System.out once we figure out that python popen thing.
