### ISSUE TITLE
K8 installation guide issue

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/twister2#687]
Following command gives an error
command 
===================
kubectl create -f https://raw.githubusercontent.com/DSC-SPIDAL/twister2/master/twister2/config/src/yaml/conf/kubernetes/deployment/twister2-dashboard-with-ps.yaml

error: unable to recognize "https://raw.githubusercontent.com/DSC-SPIDAL/twister2/master/twister2/config/src/yaml/conf/kubernetes/deployment/twister2-dashboard-wo-ps.yaml": no matches for kind "StatefulSet" in version "apps/v1beta2"

**Comment by ahmet-uyar** [comment]
it is fixed.
