### ISSUE TITLE
KeyedGather does not work on byte[] keys

### ISSUE THREAD

**Issue by pulasthi** [DSC-SPIDAL/twister2#783]
Keyed Gather operation does not work on byte[] keys, all the values are sent separately.

**Comment by chathurawidanage** [comment]
Are you running an example or your own code?

**Comment by pulasthi** [comment]
The current example does not have an byte[] key, so i added an example to the KGatherExample and ran that. Will push that example

**Comment by pulasthi** [comment]
Found the possible reason, in KGatherBatchFinalReceiver merge method we use an Hashmap and use the K value as the key into the HashMap when merging, since byte[] does not have "value equality" each K value is taken as a new value for the Map.

**Comment by chathurawidanage** [comment]
Then I think this could happen to any Key type that inherits equals and
hashcode methods from Object class.

We can write array wrappers for array types that would implement equals and
hashcode methods. Then use wrapper as the key for the hashmap. But that
would be super inefficient for large arrays.

**Comment by chathurawidanage** [comment]
@pulasthi @supunkamburugamuve any suggestions?

**Comment by pulasthi** [comment]
Yeah, that sounds like a good solution, since we already define other details such as packers in the MessageTypes class we can associate the wrapper with that too. This wrapper needs to be used at the destination selector as well (in the HashingSelector) since we again use the hashCode value to determine the target.

However, it looks like we would need to change a lot of places to correctly apply the changes. I do have a solution (hack) for the byte[] issue, maybe we can use that for the 0.4.0 release and make this change for the next release. WDYT?

**Comment by pulasthi** [comment]
fixed with pull #788
