### ISSUE TITLE
Linux Build Script Fails

### ISSUE THREAD

**Issue by vibhatha** [DSC-SPIDAL/twister2#856]
It seems certain repositories are not accessible and not found. 

`WARNING: Download from http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 501 HTTPS Required
WARNING: Download from http://maven.ibiblio.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: maven.ibiblio.org
WARNING: Download from http://repo.exist.com/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: repo.exist.com
WARNING: Download from http://www.ibiblio.net/pub/packages/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'org_apache_commons_commons_lang3':
   java.io.IOException: Error downloading [http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://maven.ibiblio.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://repo.exist.com/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://www.ibiblio.net/pub/packages/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar] to /home/vibhatha/.cache/bazel/_bazel_vibhatha/9d8bf2109b4f154fdf3b5e094b153877/external/org_apache_commons_commons_lang3/commons-lang3-3.9.jar: GET returned 404 Not Found
ERROR: /home/vibhatha/github/fork/twister2/tools/java/src/com/twitter/bazel/checkstyle/BUILD:10:1: //tools/java/src/com/twitter/bazel/checkstyle:checkstyle_java depends on @org_apache_commons_commons_lang3//jar:jar in repository @org_apache_commons_commons_lang3 which failed to fetch. no such package '@org_apache_commons_commons_lang3//jar': java.io.IOException: Error downloading [http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://maven.ibiblio.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://repo.exist.com/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://www.ibiblio.net/pub/packages/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar] to /home/vibhatha/.cache/bazel/_bazel_vibhatha/9d8bf2109b4f154fdf3b5e094b153877/external/org_apache_commons_commons_lang3/commons-lang3-3.9.jar: GET returned 404 Not Found
ERROR: Analysis of target '//scripts/package:tarpkgs' failed; build aborted: no such package '@org_apache_commons_commons_lang3//jar': java.io.IOException: Error downloading [http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://maven.ibiblio.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://repo.exist.com/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, http://www.ibiblio.net/pub/packages/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar] to /home/vibhatha/.cache/bazel/_bazel_vibhatha/9d8bf2109b4f154fdf3b5e094b153877/external/org_apache_commons_commons_lang3/commons-lang3-3.9.jar: GET returned 404 Not Found
INFO: Elapsed time: 5.500s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 18 targets configured)
`

**Comment by chathurawidanage** [comment]
It seems you are not in the latest version of master branch.

**Comment by chathurawidanage** [comment]
This issue has been already resolved in below commit.

https://github.com/DSC-SPIDAL/twister2/commit/eb3f16596ba7cd86498536570db85071c6eb30ea
